export enum TokenType {
  IDENT = "IDENT",
  NUMBER = "NUMBER",
  STRING = "STRING",
  WAIT = "WAIT",
  SET = "SET",
  REPEAT = "REPEAT",
  TIMES = "TIMES",
  AS = "AS",
  END = "END",
  VARIABLE = "VARIABLE",
  IF = "IF",
  THEN = "THEN",
  ELSE = "ELSE",
  PRINT = "PRINT",
  RANDOM = "RANDOM",
  /** Comparison operators — always space-delimited tokens, e.g. `$x > 50`. */
  OP_GT = "OP_GT",
  OP_LT = "OP_LT",
  OP_GTE = "OP_GTE",
  OP_LTE = "OP_LTE",
  OP_EQ = "OP_EQ",
  OP_NEQ = "OP_NEQ",
  /** Arithmetic operators, used in SET's optional expression form. */
  OP_PLUS = "OP_PLUS",
  OP_MINUS = "OP_MINUS",
  OP_TIMES_SIGN = "OP_TIMES_SIGN",
  OP_DIVIDE = "OP_DIVIDE",
  EOF = "EOF",
  NEWLINE = "NEWLINE",
}
