// Trimmed from server/src/packages/types.ts — only what the compiler needs.
export const COMMAND_TYPES = [
  "CAMERA_CAPTURE", "CAMERA_START_TRACKING", "CAMERA_STOP_TRACKING",
  "AUDIO_START_LISTENING", "AUDIO_STOP_LISTENING", "AUDIO_SPEAK", "AUDIO_STOP",
  "EYE_CENTER", "EYE_LEFT", "EYE_RIGHT", "EYE_SET", "EYE_TRACK_PERSON",
  "LEFT_LEG_FORWARD", "LEFT_LEG_REVERSE", "LEFT_LEG_ROTATE", "LEFT_LEG_STOP", "LEFT_LEG_JOINT", "LEFT_LEG_CENTER",
  "RIGHT_LEG_FORWARD", "RIGHT_LEG_REVERSE", "RIGHT_LEG_ROTATE", "RIGHT_LEG_STOP", "RIGHT_LEG_JOINT", "RIGHT_LEG_CENTER",
  "WALK_FORWARD", "WALK_BACKWARD", "TURN_LEFT", "TURN_RIGHT", "WALK_STOP",
  "ULTRASONIC_READ", "ULTRASONIC_CALIBRATE", "ULTRASONIC_ENABLE", "ULTRASONIC_DISABLE",
  "SERVOS_SAFE", "EMERGENCY_STOP", "EMERGENCY_CLEAR",
  "BRAIN_OBSERVE", "BRAIN_PROCESS",
  "MEMORY_SEARCH", "MEMORY_LEARN",
  "TASK_START", "TASK_CANCEL",
  "SCRIPT_COMPILE", "SCRIPT_EXECUTE",
  "FIND_PERSON", "DANCE",
  "PLAY_SONG_REQUEST", "SET_DANCE_PREFERENCE", "RESET_PERSON_FACE",
  "SMART_DEVICE_TRIGGER",
] as const;

export type CommandType = typeof COMMAND_TYPES[number];
